### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by pavanagrawal123** [aleccunningham/robinhood-react#1]
Hi!

I was trying to install this, but after running yarn install, I received this error:
module.js:472
    throw err;
    ^

Error: Cannot find module '/home/username/robinhood/src/server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/home/username/robinhood/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
[nodemon] app crashed - waiting for file changes before starting...

How can I solve this?
Thanks!

**Comment by moosh3** [comment]
Doubt it'll start up -- if you cruise through the code, you'll notice there's a lot that hasn't been hooked up yet, and I'm still refactoring the structure so it can scale well. Keep an eye out on the development, should have something running in a week or two!

**Comment by pavanagrawal123** [comment]
Sounds good! 

I recently found this UI for robinhood on Github: https://github.com/jsonmaur/robinhood-web

It doesn't do any trading, but maybe you can use this as a frontend for your thing?

I'm super excited for this project because trading on a desktop would be amazing!
Thanks.

**Comment by moosh3** [comment]
Wow! That's beautiful! Going to contact the dev. Thanks for that.
